name: Build and Release

on:
  push:
    tags:
      - "v*" # Spustí se při push tagu (v1.0.0, v1.1.0...)

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build React
        run: npm run build # Tvůj React build script

      - name: Build Electron
        run: npm run build:win

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
